import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";

const sesClient = new SESClient({ region: process.env.AWS_REGION ?? "us-east-1" });

export async function deliverEmail(
  report: { id: string; sprint_name: string },
  content: Record<string, unknown>,
  recipientEmail: string
): Promise<void> {
  const blockers = (content.blockers_and_risks as Array<{ description: string; severity: string; recommendation: string }>) ?? [];

  const htmlBody = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sprint Report: ${report.sprint_name}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 680px; margin: 0 auto; padding: 24px; background: #f5f5f5; }
    .card { background: white; border-radius: 8px; padding: 24px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    h1 { color: #0f172a; font-size: 22px; margin: 0 0 4px; }
    h2 { color: #1e40af; font-size: 15px; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 12px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 12px; font-weight: 600; }
    .badge-high { background: #fee2e2; color: #dc2626; }
    .badge-medium { background: #fef3c7; color: #d97706; }
    .badge-low { background: #dcfce7; color: #16a34a; }
    ul { padding-left: 20px; margin: 8px 0; }
    li { margin-bottom: 6px; }
    .digest-item { border-left: 3px solid #1e40af; padding-left: 12px; margin-bottom: 8px; }
    .footer { font-size: 12px; color: #64748b; text-align: center; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Sprint Report: ${report.sprint_name}</h1>
    <p style="color:#64748b;margin:0;">${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="card">
    <h2>Executive Digest</h2>
    ${(content.executive_digest as string[] ?? []).map(d => `<div class="digest-item">${d}</div>`).join("")}
  </div>

  <div class="card">
    <h2>Sprint Summary</h2>
    <p>${content.sprint_summary}</p>
  </div>

  ${(content.completed_work as string[] ?? []).length > 0 ? `
  <div class="card">
    <h2>Completed Work</h2>
    <ul>${(content.completed_work as string[]).map(w => `<li>${w}</li>`).join("")}</ul>
  </div>` : ""}

  ${blockers.length > 0 ? `
  <div class="card">
    <h2>Blockers & Risks</h2>
    ${blockers.map(b => `
      <div style="margin-bottom:12px;padding:12px;border:1px solid #e2e8f0;border-radius:6px;">
        <span class="badge badge-${b.severity}">${b.severity.toUpperCase()}</span>
        <p style="margin:6px 0;">${b.description}</p>
        <p style="margin:0;font-size:13px;color:#64748b;"><strong>Recommendation:</strong> ${b.recommendation}</p>
      </div>
    `).join("")}
  </div>` : ""}

  <div class="card">
    <h2>Metrics</h2>
    <p>${content.metrics_narrative}</p>
  </div>

  ${(content.action_items as string[] ?? []).length > 0 ? `
  <div class="card">
    <h2>Action Items</h2>
    <ol>${(content.action_items as string[]).map(a => `<li>${a}</li>`).join("")}</ol>
  </div>` : ""}

  <div class="footer">
    Generated by SprintPulse | Report ID: ${report.id} | <a href="#" style="color:#1e40af;">View in SprintPulse</a>
  </div>
</body>
</html>`;

  await sesClient.send(new SendEmailCommand({
    Source: process.env.AWS_SES_FROM_EMAIL ?? "reports@sprintpulse.io",
    Destination: { ToAddresses: [recipientEmail] },
    Message: {
      Subject: { Data: `Sprint Report: ${report.sprint_name}`, Charset: "UTF-8" },
      Body: {
        Html: { Data: htmlBody, Charset: "UTF-8" },
        Text: { Data: `Sprint Report: ${report.sprint_name}\n\n${content.sprint_summary}`, Charset: "UTF-8" },
      },
    },
  }));
}
