import { WebClient } from "@slack/web-api";

const slackClient = new WebClient(process.env.SLACK_BOT_TOKEN);

interface BlockerRisk {
  description: string;
  severity: string;
  recommendation: string;
}

export async function deliverSlack(
  report: { id: string; sprint_name: string },
  content: Record<string, unknown>,
  channelId: string
): Promise<void> {
  const blockers = (content.blockers_and_risks as BlockerRisk[]) ?? [];
  const highBlockers = blockers.filter(b => b.severity === "high");

  const blocks = [
    {
      type: "header",
      text: { type: "plain_text", text: `📊 Sprint Report: ${report.sprint_name}`, emoji: true },
    },
    { type: "divider" },
    {
      type: "section",
      text: { type: "mrkdwn", text: `*Summary*\n${content.sprint_summary}` },
    },
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*Executive Digest*\n${(content.executive_digest as string[])?.map(d => `• ${d}`).join("\n") ?? ""}` },
      ],
    },
    ...(content.completed_work as string[])?.length > 0 ? [{
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Completed Work*\n${(content.completed_work as string[]).map(w => `• ${w}`).join("\n")}`,
      },
    }] : [],
    ...(blockers.length > 0 ? [{
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Blockers & Risks*\n${blockers.map(b => `${b.severity === "high" ? "🔴" : b.severity === "medium" ? "🟡" : "🟢"} ${b.description}`).join("\n")}`,
      },
    }] : []),
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Metrics*\n${content.metrics_narrative}`,
      },
    },
    ...(content.action_items as string[])?.length > 0 ? [{
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Action Items*\n${(content.action_items as string[]).map((a, i) => `${i + 1}. ${a}`).join("\n")}`,
      },
    }] : [],
    { type: "divider" },
    {
      type: "context",
      elements: [
        { type: "mrkdwn", text: `Report ID: ${report.id} | Generated by SprintPulse` },
      ],
    },
  ];

  await slackClient.chat.postMessage({
    channel: channelId,
    blocks,
    text: `Sprint Report: ${report.sprint_name}`,
    unfurl_links: false,
  });

  if (highBlockers.length > 0) {
    await slackClient.chat.postMessage({
      channel: channelId,
      text: `⚠️ *${highBlockers.length} HIGH severity blocker(s) require immediate attention:*\n${highBlockers.map(b => `• ${b.description}\n  _Recommendation: ${b.recommendation}_`).join("\n")}`,
    });
  }
}
